---
matches:
  # Simple text replacement
  - trigger: ";espanso"
    replace: "Hi there!"

  - trigger: ";mail"
    replace: "chrysanthos@rouvellas.com"

  - trigger: ";gail"
    replace: "c.rouvellas@gmail.com"
  
  - trigger: "lqc"
    replace: "Let me know if you have any questions or concerns."

  - trigger: "tiaf"
    replace: "Thanks in advance for your time."

  - trigger: "tc4m"
    replace: "I send this email at a time that is convenient to me. I do not expect you to respond outside of your working hours."

  - trigger: ";tel"
    replace: "(289) 683-1510"

  - trigger: ";bol"
    label: "Markdown - Bold"
    replace: "**$|$**"

  - trigger: ";ita"
    label: "Markdown - Italic"
    replace: "*$|$*"

  - trigger: ";--"
    label: "Markdown - Strikethrough"
    replace: "~~$|$~~"

  - trigger: ";url:"
    label: "Markdown - URL"
    replace: "[$|$]()"

  - trigger: ";img:"
    label: "Markdown - Image"
    replace: "![]($|$)"

  - trigger: ";task:"
    label: "Markdown - Task"
    replace: "- [ ] "

  - trigger: ";taskdone:"
    label: "Markdown - Task completed"
    replace: "- [x] "

  - trigger: ";comment:"
    label: "Markdown - Comment"
    replace: "<!--- $|$ -->"
    force_clipboard: true

  # Multi-line text replacement
  - trigger: ";trig"
    replace: |
              - trigger: ""
                replace: "$|$"

  - trigger: ";block:"
    label: "Markdown - Code block"
    replace: |-
        ```
        $|$
        ```
    force_clipboard: true

  - trigger: ";code:"
    label: "Markdown - Inline code"
    replace: |-
        `$|$`
    force_clipboard: true

  - trigger: ";collapse:"
    label: "Markdown - Collapse block"
    replace: |-
        <details>
        <summary></summary>
        $|$
        </details>
    force_clipboard: true



  # Clipboard usage

  - trigger: ";mdl"
    replace: "[$|$]({{clipb}})"
    vars:
      - name: "clipb"
        type: "clipboard"





  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"


  # Print the output of a shell command
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Scripts
  - trigger: "ippa"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/ip_tools.py"

  - trigger: ";rs"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/remove_symbols.py"

  - trigger: ";mdtb"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/mdtable.py"
...
