[font]
size = 11.0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[window]
decorations = "None"
opacity = 0.67
startup_mode = "Fullscreen"

[bell]
animation ="Linear"
duration = 1
color = "#FFFFFF"

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_timeout = 0
unfocused_hollow = false
